### ISSUE TITLE
CMOOSCommsClient::Notify does not have an overload for int

### ISSUE THREAD

**Issue by tsaubergine** [themoos/core-moos#10]
CMOOSCommsClient::Notify("foo", 3) will not compile (at least on g++ 4.7.3-1ubuntu1) because the second parameter is an int, and there is no overload for int. 

Notify called with an int used to implicitly cast to double in pre-10 versions of MOOS. This behavior should be restored.

**Comment by arh-oxbotica** [comment]
I know this is a very old issue now... but I can't replicate the problem. I'm not aware of any reason that the compiler wouldn't be able to do an implicit cast in this case. Specifically this works fine on recent compilers:
```
CMOOSCommClient client;
client.Notify("foo", 3);
```

The specific code snippet that you give: `CMOOSCommClient::Notify("foo", 3);` will fail because `Notify` is not a static method.
