### ISSUE TITLE
 Questionable references to suicide and massacre in ktm help

### ISSUE THREAD

**Issue by adamish** [themoos/core-moos#68]
Minor point but not sure whether the tone in this help is appropriate in https://github.com/themoos/core-moos/blob/24942423ce3f3ebdb3cee876edb71bdd04dc5555/Core/tools/ktm/ktm.cpp

```
void PrintHelpAndExit()
{
    std::cerr<<"Kill The MOOS (ktm)\n";
    std::cerr<<"--channel=<address>    address to issue kill on \n";
    std::cerr<<"--port=<int>           port to issue kill on \n";
    std::cerr<<"--phrase=<string>      pass phrase which Suicide listeners are keyed to\n";
    std::cerr<<"--all                  pass to network, it is a massacre\n";
    std::cerr<<"--query                find out who would jump\n";
    std::cerr<<"--name=<string>        only apply if matches pattern\n";
```

**Comment by NeedsMoar** [comment]
This file hasn't been touched in 10 years, the project in 4, nobody is going to do anything to pretty this up for you.

I find nothing wrong with it though, it's in a file called "Kill the moose", it's kind of an amusing continuation of a theme.  

Also, suicide and massacre are the questionable references, but kill is ok?   Interesting since if we're doing hypothetical psychoanalsis of a paranoid or delusional schizophrenic internalizing everything, the usage of "kill" is worse since it is used in the first line as a directive, which is more likely to be misinterpreted and internalized.  The other words and other uses of kill are explicit references to things in context in the software;   _address_ to issue kill, _port__, _pass phrase which_ Suicide listeners..., when killing _all_ addresses and ports, _it is a_ massacre, when checking for instances that this would affect, _find out who would_ jump.  Yeah, the words are there, but they can't be taken out of context due to the sentence construction.  There are levels of mental disorder where simply seeing the word would cause distress, from experience, but (also from experience) if you're that far gone you can't be on the internet at all.  For every 3 obviously violent words there would have been 100 more that you'd never even think to associate with violence that I had adopted as bizarre underhanded personal insults directed at me.  I bring that up since I'm back to being basically sane now at least as far as distorted thought processes go and words like this don't have any real affect on the happy or the severely depressed, you'll immediately get slapped with something 10x as bad if you dare see a movie or a trailer for one.   
Even if you eliminate all of that, the English language and most Western languages (I can't speak Chinese or Japanese so I don't know their inbuilt tendencies) were formed slowly and during what amounted to an extended 2000 year stretch of horrifying poverty, violence, and death for 99% of humanity.  It is almost impossible to avoid embedding some sort of violent idiom or language into ordinary conversation.  Some languages tend towards this more than others, but it's part of all of them because more words will always be created for experience than fantasy.  
Plus, once again, this is what I consider to be one of the best uses of awful language -- invalidating it by making a joke of it.   It isn't directed at anyone or attacking any group, so my opinion would be that changing it only helps push violent language into an area of having even more power.  Only what happens should have power, or violent language constructed as _threats_.  

Now if you'll excuse me I'm going to nip off and dig up Ronald Reagan and put a few rounds in his corpse to get the neighbor's dog to shut the hell up and quit nagging me about it.  I keep telling the mutt he died years ago but it's just a dumb dog so I might as well go through the motions... /s

**Comment by adamish** [comment]
Nice try to justify this
